# Generated by Django 5.0.2 on 2024-02-20 20:33

import apps.root.models.common
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '__first__'),
        ('journal', '__first__'),
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('scrap_weight', models.PositiveSmallIntegerField(default=0, verbose_name='Прием лома, кг')),
                ('scrap_value', models.PositiveIntegerField(default=0, verbose_name='Оценка лома')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена (полная)')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка (не лом)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('day', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='journal.day', verbose_name='День')),
                ('fellow', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='root.fellow', verbose_name='Сотрудник')),
                ('product', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-day__date', 'sort_order'],
            },
            bases=(apps.root.models.common.DayMixin, models.Model),
        ),
    ]
