# Generated by Django 5.0.2 on 2024-02-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_scrap_value_alter_sale_scrap_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Комиссии, скидки'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена полная (за 1 ед.)'),
        ),
    ]
