# Generated by Django 5.0.2 on 2024-02-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_discount_alter_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='scrap_quantity',
            field=models.SmallIntegerField(default=0, verbose_name='Лом, штуки'),
        ),
    ]
