# Generated by Django 5.0.2 on 2024-02-20 20:33

import apps.root.models.common
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '__first__'),
        ('journal', '__first__'),
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('scrap_weight', models.PositiveSmallIntegerField(default=0, verbose_name='Прием лома, кг')),
                ('scrap_value', models.PositiveIntegerField(default=0, verbose_name='Оценка лома')),
                ('number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер накладной')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты')),
                ('day', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='journal.day', verbose_name='День')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='root.partner', verbose_name='Партнёр, поставщик')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
                'ordering': ['-day__date', 'sort_order'],
            },
            bases=(apps.root.models.common.DayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Цена закупки')),
                ('invoice', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.invoice', verbose_name='Закупка')),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['sort_order'],
            },
        ),
    ]
