# Generated by Django 5.0.2 on 2024-02-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата накладной'),
        ),
    ]
