# Generated by Django 5.0.4 on 2024-04-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_invoice_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Начиная с...')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цена лома',
                'verbose_name_plural': 'Цены лома',
                'ordering': ['date_from'],
            },
        ),
    ]
