# Generated by Django 5.0.2 on 2024-02-20 20:33

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
        ('sales', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('account', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply', to='root.account', verbose_name='Счёт')),
                ('invoice', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stock.invoice', verbose_name='Закупка')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('account', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='root.account', verbose_name='Счёт')),
                ('sale', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='Продажа')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
