# Generated by Django 5.0.2 on 2024-02-23 22:22

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('journal', '0002_alter_sourcedoc_name'),
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип расходов',
                'verbose_name_plural': 'Типы расходов',
            },
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('day', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='journal.day', verbose_name='День')),
                ('fellow', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='root.fellow', verbose_name='Сотрудник')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='root.partner', verbose_name='Партнёр, поставщик')),
                ('cost_type', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='finance.costtype', verbose_name='Тип расходов')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='CostPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('account', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='root.account', verbose_name='Счёт')),
                ('cost', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.cost', verbose_name='Расход')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
