# Generated by Django 5.0.2 on 2024-02-24 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_costtype_invoicepayment_date_salepayment_date_cost_and_more'),
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='fellow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='root.fellow', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='costpayment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='root.account', verbose_name='Счёт'),
        ),
        migrations.AlterField(
            model_name='invoicepayment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply', to='root.account', verbose_name='Счёт'),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='root.account', verbose_name='Счёт'),
        ),
    ]
