# Generated by Django 5.0.2 on 2024-02-20 20:33

import apps.journal.models.source_doc
import apps.root.models.common
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'День',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Журнал',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Месяц',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Год',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SourceDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('source_doc_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Накладная'), (2, 'Журнал')], null=True, verbose_name='Тип документа')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('document', models.FileField(upload_to=apps.journal.models.source_doc.SourceDoc.upload_to, verbose_name='Файл')),
                ('day', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_docs', to='journal.day', verbose_name='День')),
            ],
            options={
                'verbose_name': 'Первичный документ',
                'verbose_name_plural': 'Первичные документы',
                'ordering': ['day__date', 'sort_order'],
            },
            bases=(apps.root.models.common.DayMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Начало смены')),
                ('end_time', models.TimeField(verbose_name='Окончание смены')),
                ('day', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='journal.day', verbose_name='День')),
                ('fellow', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_shifts', to='root.fellow', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Рабочая смена',
                'verbose_name_plural': 'Рабочая смена',
            },
        ),
    ]
