# Generated by Django 5.0.2 on 2024-02-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcedoc',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Название'),
        ),
    ]
