# Generated by Django 5.0.2 on 2024-02-24 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_sourcedoc_name'),
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='fellow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_shifts', to='root.fellow', verbose_name='Сотрудник'),
        ),
    ]
