# Generated by Django 5.0.2 on 2024-02-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'АКБ'), (2, 'Аксессуар'), (3, 'Услуга'), (4, 'Мото АКБ')], default=1, null=True, verbose_name='Секция'),
        ),
    ]
