# Generated by Django 5.0.2 on 2024-02-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='publish',
            new_name='published',
        ),
    ]
