# Generated by Django 5.0.4 on 2024-04-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_publish_product_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Аккумулятор автомобильный'), (2, 'Аксессуар'), (3, 'Услуга'), (4, 'Аккумулятор для мотоцикла')], default=1, null=True, verbose_name='Секция'),
        ),
    ]
