# Generated by Django 5.0.4 on 2024-05-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_case_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='silver',
            field=models.BooleanField(default=False, verbose_name='Silver'),
        ),
        migrations.AlterField(
            model_name='product',
            name='calcium',
            field=models.BooleanField(default=False, verbose_name='Ca-Ca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_size',
            field=models.CharField(blank=True, choices=[('L1', 'L1'), ('LB1', 'LB1'), ('L2', 'L2'), ('LB2', 'LB2'), ('L3', 'L3'), ('LB3', 'LB3'), ('L4', 'L4'), ('LB4', 'LB4'), ('L5', 'L5'), ('LB5', 'LB5'), ('L6', 'L6'), ('B19', 'B19'), ('B24', 'B24'), ('D23', 'D23'), ('D26', 'D26'), ('D31', 'D31'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D5', 'D5')], max_length=16, null=True, verbose_name='Типоразмер'),
        ),
    ]
